name: Run Static Checks and Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  go-test:
    name: Go Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Run all short tests
        shell: devenv shell bash -- -e {0}
        run: |
          go test -short ./...

  static-go-checks:
    name: Static Go Checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Check go.mod is tidy
        shell: devenv shell bash -- -e {0}
        run: |
          go mod tidy
          git diff --exit-code

      - name: Check *_templ.go files are up-to-date
        shell: devenv shell bash -- -e {0}
        run: |
          go tool templ generate
          git diff --exit-code

      - name: Run golangci-lint
        shell: devenv shell bash -- -e {0}
        run: |
          golangci-lint run

  generated-code-checks:
    name: Generated Code Checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Run generated code checks in Justfile
        shell: devenv shell bash -- -e {0}
        run: |
          just gen
          git diff --exit-code
